services:
  postgres:
    image: postgres:15.13-bookworm
    restart: always
    volumes:
      - type: bind
        source: ./postgres/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres/init-db
        target: /docker-entrypoint-initdb.d
    networks:
      - backend
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: changeit


  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    restart: always
    command: start-dev --import-realm
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8443:8443
    volumes:
      - type: bind
        source: ./keycloak/conf
        target: /opt/keycloak/conf
      - type: bind
        source: ./keycloak/themes
        target: /opt/keycloak/themes
      - type: bind
        source: ./keycloak/providers
        target: /opt/keycloak/providers
      - type: bind
        source: ./keycloak/data
        target: /opt/keycloak/data
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changeit
      KC_DB_SCHEMA: keycloak
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_HEALTH: enabled
      KC_METRICS: enabled
      

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - 127.0.0.1:8081:8080
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
